package com.missionhub.android.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.missionhub.android.model.User;
import com.missionhub.android.model.Person;
import com.missionhub.android.model.Address;
import com.missionhub.android.model.EmailAddress;
import com.missionhub.android.model.PhoneNumber;
import com.missionhub.android.model.Organization;
import com.missionhub.android.model.Role;
import com.missionhub.android.model.OrganizationalRole;
import com.missionhub.android.model.ContactAssignment;
import com.missionhub.android.model.Group;
import com.missionhub.android.model.FollowupComment;
import com.missionhub.android.model.Rejoicable;
import com.missionhub.android.model.Question;
import com.missionhub.android.model.Survey;
import com.missionhub.android.model.SmsKeyword;
import com.missionhub.android.model.AnswerSheet;
import com.missionhub.android.model.Answer;
import com.missionhub.android.model.Setting;
import com.missionhub.android.model.UserSetting;

import com.missionhub.android.model.UserDao;
import com.missionhub.android.model.PersonDao;
import com.missionhub.android.model.AddressDao;
import com.missionhub.android.model.EmailAddressDao;
import com.missionhub.android.model.PhoneNumberDao;
import com.missionhub.android.model.OrganizationDao;
import com.missionhub.android.model.RoleDao;
import com.missionhub.android.model.OrganizationalRoleDao;
import com.missionhub.android.model.ContactAssignmentDao;
import com.missionhub.android.model.GroupDao;
import com.missionhub.android.model.FollowupCommentDao;
import com.missionhub.android.model.RejoicableDao;
import com.missionhub.android.model.QuestionDao;
import com.missionhub.android.model.SurveyDao;
import com.missionhub.android.model.SmsKeywordDao;
import com.missionhub.android.model.AnswerSheetDao;
import com.missionhub.android.model.AnswerDao;
import com.missionhub.android.model.SettingDao;
import com.missionhub.android.model.UserSettingDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig personDaoConfig;
    private final DaoConfig addressDaoConfig;
    private final DaoConfig emailAddressDaoConfig;
    private final DaoConfig phoneNumberDaoConfig;
    private final DaoConfig organizationDaoConfig;
    private final DaoConfig roleDaoConfig;
    private final DaoConfig organizationalRoleDaoConfig;
    private final DaoConfig contactAssignmentDaoConfig;
    private final DaoConfig groupDaoConfig;
    private final DaoConfig followupCommentDaoConfig;
    private final DaoConfig rejoicableDaoConfig;
    private final DaoConfig questionDaoConfig;
    private final DaoConfig surveyDaoConfig;
    private final DaoConfig smsKeywordDaoConfig;
    private final DaoConfig answerSheetDaoConfig;
    private final DaoConfig answerDaoConfig;
    private final DaoConfig settingDaoConfig;
    private final DaoConfig userSettingDaoConfig;

    private final UserDao userDao;
    private final PersonDao personDao;
    private final AddressDao addressDao;
    private final EmailAddressDao emailAddressDao;
    private final PhoneNumberDao phoneNumberDao;
    private final OrganizationDao organizationDao;
    private final RoleDao roleDao;
    private final OrganizationalRoleDao organizationalRoleDao;
    private final ContactAssignmentDao contactAssignmentDao;
    private final GroupDao groupDao;
    private final FollowupCommentDao followupCommentDao;
    private final RejoicableDao rejoicableDao;
    private final QuestionDao questionDao;
    private final SurveyDao surveyDao;
    private final SmsKeywordDao smsKeywordDao;
    private final AnswerSheetDao answerSheetDao;
    private final AnswerDao answerDao;
    private final SettingDao settingDao;
    private final UserSettingDao userSettingDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        addressDaoConfig = daoConfigMap.get(AddressDao.class).clone();
        addressDaoConfig.initIdentityScope(type);

        emailAddressDaoConfig = daoConfigMap.get(EmailAddressDao.class).clone();
        emailAddressDaoConfig.initIdentityScope(type);

        phoneNumberDaoConfig = daoConfigMap.get(PhoneNumberDao.class).clone();
        phoneNumberDaoConfig.initIdentityScope(type);

        organizationDaoConfig = daoConfigMap.get(OrganizationDao.class).clone();
        organizationDaoConfig.initIdentityScope(type);

        roleDaoConfig = daoConfigMap.get(RoleDao.class).clone();
        roleDaoConfig.initIdentityScope(type);

        organizationalRoleDaoConfig = daoConfigMap.get(OrganizationalRoleDao.class).clone();
        organizationalRoleDaoConfig.initIdentityScope(type);

        contactAssignmentDaoConfig = daoConfigMap.get(ContactAssignmentDao.class).clone();
        contactAssignmentDaoConfig.initIdentityScope(type);

        groupDaoConfig = daoConfigMap.get(GroupDao.class).clone();
        groupDaoConfig.initIdentityScope(type);

        followupCommentDaoConfig = daoConfigMap.get(FollowupCommentDao.class).clone();
        followupCommentDaoConfig.initIdentityScope(type);

        rejoicableDaoConfig = daoConfigMap.get(RejoicableDao.class).clone();
        rejoicableDaoConfig.initIdentityScope(type);

        questionDaoConfig = daoConfigMap.get(QuestionDao.class).clone();
        questionDaoConfig.initIdentityScope(type);

        surveyDaoConfig = daoConfigMap.get(SurveyDao.class).clone();
        surveyDaoConfig.initIdentityScope(type);

        smsKeywordDaoConfig = daoConfigMap.get(SmsKeywordDao.class).clone();
        smsKeywordDaoConfig.initIdentityScope(type);

        answerSheetDaoConfig = daoConfigMap.get(AnswerSheetDao.class).clone();
        answerSheetDaoConfig.initIdentityScope(type);

        answerDaoConfig = daoConfigMap.get(AnswerDao.class).clone();
        answerDaoConfig.initIdentityScope(type);

        settingDaoConfig = daoConfigMap.get(SettingDao.class).clone();
        settingDaoConfig.initIdentityScope(type);

        userSettingDaoConfig = daoConfigMap.get(UserSettingDao.class).clone();
        userSettingDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        personDao = new PersonDao(personDaoConfig, this);
        addressDao = new AddressDao(addressDaoConfig, this);
        emailAddressDao = new EmailAddressDao(emailAddressDaoConfig, this);
        phoneNumberDao = new PhoneNumberDao(phoneNumberDaoConfig, this);
        organizationDao = new OrganizationDao(organizationDaoConfig, this);
        roleDao = new RoleDao(roleDaoConfig, this);
        organizationalRoleDao = new OrganizationalRoleDao(organizationalRoleDaoConfig, this);
        contactAssignmentDao = new ContactAssignmentDao(contactAssignmentDaoConfig, this);
        groupDao = new GroupDao(groupDaoConfig, this);
        followupCommentDao = new FollowupCommentDao(followupCommentDaoConfig, this);
        rejoicableDao = new RejoicableDao(rejoicableDaoConfig, this);
        questionDao = new QuestionDao(questionDaoConfig, this);
        surveyDao = new SurveyDao(surveyDaoConfig, this);
        smsKeywordDao = new SmsKeywordDao(smsKeywordDaoConfig, this);
        answerSheetDao = new AnswerSheetDao(answerSheetDaoConfig, this);
        answerDao = new AnswerDao(answerDaoConfig, this);
        settingDao = new SettingDao(settingDaoConfig, this);
        userSettingDao = new UserSettingDao(userSettingDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Person.class, personDao);
        registerDao(Address.class, addressDao);
        registerDao(EmailAddress.class, emailAddressDao);
        registerDao(PhoneNumber.class, phoneNumberDao);
        registerDao(Organization.class, organizationDao);
        registerDao(Role.class, roleDao);
        registerDao(OrganizationalRole.class, organizationalRoleDao);
        registerDao(ContactAssignment.class, contactAssignmentDao);
        registerDao(Group.class, groupDao);
        registerDao(FollowupComment.class, followupCommentDao);
        registerDao(Rejoicable.class, rejoicableDao);
        registerDao(Question.class, questionDao);
        registerDao(Survey.class, surveyDao);
        registerDao(SmsKeyword.class, smsKeywordDao);
        registerDao(AnswerSheet.class, answerSheetDao);
        registerDao(Answer.class, answerDao);
        registerDao(Setting.class, settingDao);
        registerDao(UserSetting.class, userSettingDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        personDaoConfig.getIdentityScope().clear();
        addressDaoConfig.getIdentityScope().clear();
        emailAddressDaoConfig.getIdentityScope().clear();
        phoneNumberDaoConfig.getIdentityScope().clear();
        organizationDaoConfig.getIdentityScope().clear();
        roleDaoConfig.getIdentityScope().clear();
        organizationalRoleDaoConfig.getIdentityScope().clear();
        contactAssignmentDaoConfig.getIdentityScope().clear();
        groupDaoConfig.getIdentityScope().clear();
        followupCommentDaoConfig.getIdentityScope().clear();
        rejoicableDaoConfig.getIdentityScope().clear();
        questionDaoConfig.getIdentityScope().clear();
        surveyDaoConfig.getIdentityScope().clear();
        smsKeywordDaoConfig.getIdentityScope().clear();
        answerSheetDaoConfig.getIdentityScope().clear();
        answerDaoConfig.getIdentityScope().clear();
        settingDaoConfig.getIdentityScope().clear();
        userSettingDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

    public AddressDao getAddressDao() {
        return addressDao;
    }

    public EmailAddressDao getEmailAddressDao() {
        return emailAddressDao;
    }

    public PhoneNumberDao getPhoneNumberDao() {
        return phoneNumberDao;
    }

    public OrganizationDao getOrganizationDao() {
        return organizationDao;
    }

    public RoleDao getRoleDao() {
        return roleDao;
    }

    public OrganizationalRoleDao getOrganizationalRoleDao() {
        return organizationalRoleDao;
    }

    public ContactAssignmentDao getContactAssignmentDao() {
        return contactAssignmentDao;
    }

    public GroupDao getGroupDao() {
        return groupDao;
    }

    public FollowupCommentDao getFollowupCommentDao() {
        return followupCommentDao;
    }

    public RejoicableDao getRejoicableDao() {
        return rejoicableDao;
    }

    public QuestionDao getQuestionDao() {
        return questionDao;
    }

    public SurveyDao getSurveyDao() {
        return surveyDao;
    }

    public SmsKeywordDao getSmsKeywordDao() {
        return smsKeywordDao;
    }

    public AnswerSheetDao getAnswerSheetDao() {
        return answerSheetDao;
    }

    public AnswerDao getAnswerDao() {
        return answerDao;
    }

    public SettingDao getSettingDao() {
        return settingDao;
    }

    public UserSettingDao getUserSettingDao() {
        return userSettingDao;
    }

}
