package com.missionhub.api.model.sql;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.Query;
import de.greenrobot.dao.QueryBuilder;

import com.missionhub.api.model.sql.FollowupComment;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table FOLLOWUP_COMMENT.
*/
public class FollowupCommentDao extends AbstractDao<FollowupComment, Long> {

    public static final String TABLENAME = "FOLLOWUP_COMMENT";

    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Contact_id = new Property(1, Long.class, "contact_id", false, "CONTACT_ID");
        public final static Property Commenter_id = new Property(2, Long.class, "commenter_id", false, "COMMENTER_ID");
        public final static Property Organization_id = new Property(3, Long.class, "organization_id", false, "ORGANIZATION_ID");
        public final static Property Comment = new Property(4, String.class, "comment", false, "COMMENT");
        public final static Property Status = new Property(5, String.class, "status", false, "STATUS");
        public final static Property Created_at = new Property(6, java.util.Date.class, "created_at", false, "CREATED_AT");
        public final static Property Updated_at = new Property(7, java.util.Date.class, "updated_at", false, "UPDATED_AT");
        public final static Property Deleted_at = new Property(8, java.util.Date.class, "deleted_at", false, "DELETED_AT");
    };

    private DaoSession daoSession;

    private Query<FollowupComment> person_Followup_commentsQuery;
    private Query<FollowupComment> person_Posted_commentsQuery;
    private Query<FollowupComment> organization_FollowupCommentListQuery;

    public FollowupCommentDao(DaoConfig config) {
        super(config);
    }
    
    public FollowupCommentDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String sql = "CREATE TABLE " + (ifNotExists? "IF NOT EXISTS ": "") + "'FOLLOWUP_COMMENT' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'CONTACT_ID' INTEGER," + // 1: contact_id
                "'COMMENTER_ID' INTEGER," + // 2: commenter_id
                "'ORGANIZATION_ID' INTEGER," + // 3: organization_id
                "'COMMENT' TEXT," + // 4: comment
                "'STATUS' TEXT," + // 5: status
                "'CREATED_AT' INTEGER," + // 6: created_at
                "'UPDATED_AT' INTEGER," + // 7: updated_at
                "'DELETED_AT' INTEGER);"; // 8: deleted_at
        db.execSQL(sql);
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'FOLLOWUP_COMMENT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, FollowupComment entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long contact_id = entity.getContact_id();
        if (contact_id != null) {
            stmt.bindLong(2, contact_id);
        }
 
        Long commenter_id = entity.getCommenter_id();
        if (commenter_id != null) {
            stmt.bindLong(3, commenter_id);
        }
 
        Long organization_id = entity.getOrganization_id();
        if (organization_id != null) {
            stmt.bindLong(4, organization_id);
        }
 
        String comment = entity.getComment();
        if (comment != null) {
            stmt.bindString(5, comment);
        }
 
        String status = entity.getStatus();
        if (status != null) {
            stmt.bindString(6, status);
        }
 
        java.util.Date created_at = entity.getCreated_at();
        if (created_at != null) {
            stmt.bindLong(7, created_at.getTime());
        }
 
        java.util.Date updated_at = entity.getUpdated_at();
        if (updated_at != null) {
            stmt.bindLong(8, updated_at.getTime());
        }
 
        java.util.Date deleted_at = entity.getDeleted_at();
        if (deleted_at != null) {
            stmt.bindLong(9, deleted_at.getTime());
        }
    }

    @Override
    protected void attachEntity(FollowupComment entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public FollowupComment readEntity(Cursor cursor, int offset) {
        FollowupComment entity = new FollowupComment( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // contact_id
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // commenter_id
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // organization_id
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // comment
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // status
            cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)), // created_at
            cursor.isNull(offset + 7) ? null : new java.util.Date(cursor.getLong(offset + 7)), // updated_at
            cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)) // deleted_at
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, FollowupComment entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setContact_id(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setCommenter_id(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setOrganization_id(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setComment(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setStatus(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setCreated_at(cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)));
        entity.setUpdated_at(cursor.isNull(offset + 7) ? null : new java.util.Date(cursor.getLong(offset + 7)));
        entity.setDeleted_at(cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)));
     }
    
    @Override
    protected Long updateKeyAfterInsert(FollowupComment entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(FollowupComment entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "followup_comments" to-many relationship of Person. */
    public synchronized List<FollowupComment> _queryPerson_Followup_comments(Long contact_id) {
        if (person_Followup_commentsQuery == null) {
            QueryBuilder<FollowupComment> queryBuilder = queryBuilder();
            queryBuilder.where(Properties.Contact_id.eq(contact_id));
            person_Followup_commentsQuery = queryBuilder.build();
        } else {
            person_Followup_commentsQuery.setParameter(0, contact_id);
        }
        return person_Followup_commentsQuery.list();
    }

    /** Internal query to resolve the "posted_comments" to-many relationship of Person. */
    public synchronized List<FollowupComment> _queryPerson_Posted_comments(Long commenter_id) {
        if (person_Posted_commentsQuery == null) {
            QueryBuilder<FollowupComment> queryBuilder = queryBuilder();
            queryBuilder.where(Properties.Commenter_id.eq(commenter_id));
            person_Posted_commentsQuery = queryBuilder.build();
        } else {
            person_Posted_commentsQuery.setParameter(0, commenter_id);
        }
        return person_Posted_commentsQuery.list();
    }

    /** Internal query to resolve the "followupCommentList" to-many relationship of Organization. */
    public synchronized List<FollowupComment> _queryOrganization_FollowupCommentList(Long organization_id) {
        if (organization_FollowupCommentListQuery == null) {
            QueryBuilder<FollowupComment> queryBuilder = queryBuilder();
            queryBuilder.where(Properties.Organization_id.eq(organization_id));
            organization_FollowupCommentListQuery = queryBuilder.build();
        } else {
            organization_FollowupCommentListQuery.setParameter(0, organization_id);
        }
        return organization_FollowupCommentListQuery.list();
    }

}
