package com.missionhub.api.model.sql;

import java.util.List;
import com.missionhub.api.model.sql.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GROUPS.
 */
public class Group {

    private Long id;
    private String name;
    private String location;
    private String meets;
    private Integer start_time;
    private Integer end_time;
    private Long organization_id;
    private java.util.Date created_at;
    private java.util.Date updated_at;
    private Boolean list_publicly;
    private Boolean approve_join_requests;

    /** Used to resolve relations */
    private DaoSession daoSession;

    /** Used for active entity operations. */
    private GroupDao myDao;

    private Organization organization;
    private Long organization__resolvedKey;

    private List<GroupMembership> members;

    public Group() {
    }

    public Group(Long id) {
        this.id = id;
    }

    public Group(Long id, String name, String location, String meets, Integer start_time, Integer end_time, Long organization_id, java.util.Date created_at, java.util.Date updated_at, Boolean list_publicly, Boolean approve_join_requests) {
        this.id = id;
        this.name = name;
        this.location = location;
        this.meets = meets;
        this.start_time = start_time;
        this.end_time = end_time;
        this.organization_id = organization_id;
        this.created_at = created_at;
        this.updated_at = updated_at;
        this.list_publicly = list_publicly;
        this.approve_join_requests = approve_join_requests;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getGroupDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getMeets() {
        return meets;
    }

    public void setMeets(String meets) {
        this.meets = meets;
    }

    public Integer getStart_time() {
        return start_time;
    }

    public void setStart_time(Integer start_time) {
        this.start_time = start_time;
    }

    public Integer getEnd_time() {
        return end_time;
    }

    public void setEnd_time(Integer end_time) {
        this.end_time = end_time;
    }

    public Long getOrganization_id() {
        return organization_id;
    }

    public void setOrganization_id(Long organization_id) {
        this.organization_id = organization_id;
    }

    public java.util.Date getCreated_at() {
        return created_at;
    }

    public void setCreated_at(java.util.Date created_at) {
        this.created_at = created_at;
    }

    public java.util.Date getUpdated_at() {
        return updated_at;
    }

    public void setUpdated_at(java.util.Date updated_at) {
        this.updated_at = updated_at;
    }

    public Boolean getList_publicly() {
        return list_publicly;
    }

    public void setList_publicly(Boolean list_publicly) {
        this.list_publicly = list_publicly;
    }

    public Boolean getApprove_join_requests() {
        return approve_join_requests;
    }

    public void setApprove_join_requests(Boolean approve_join_requests) {
        this.approve_join_requests = approve_join_requests;
    }

    /** To-one relationship, resolved on first access. */
    public Organization getOrganization() {
        if (organization__resolvedKey == null || !organization__resolvedKey.equals(organization_id)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            OrganizationDao targetDao = daoSession.getOrganizationDao();
            organization = targetDao.load(organization_id);
            organization__resolvedKey = organization_id;
        }
        return organization;
    }

    public void setOrganization(Organization organization) {
        this.organization = organization;
        organization_id = organization == null ? null : organization.getId();
        organization__resolvedKey = organization_id;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public synchronized List<GroupMembership> getMembers() {
        if (members == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            GroupMembershipDao targetDao = daoSession.getGroupMembershipDao();
            members = targetDao._queryGroup_Members(id);
        }
        return members;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetMembers() {
        members = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
