package com.missionhub.api.model.sql;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.Query;
import de.greenrobot.dao.QueryBuilder;

import com.missionhub.api.model.sql.OrganizationalRole;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ORGANIZATIONAL_ROLE.
*/
public class OrganizationalRoleDao extends AbstractDao<OrganizationalRole, Integer> {

    public static final String TABLENAME = "ORGANIZATIONAL_ROLE";

    public static class Properties {
        public final static Property _id = new Property(0, Integer.class, "_id", true, "_ID");
        public final static Property Person_id = new Property(1, Integer.class, "person_id", false, "PERSON_ID");
        public final static Property Org_id = new Property(2, Integer.class, "org_id", false, "ORG_ID");
        public final static Property Role = new Property(3, String.class, "role", false, "ROLE");
        public final static Property Name = new Property(4, String.class, "name", false, "NAME");
        public final static Property Primary = new Property(5, Boolean.class, "primary", false, "PRIMARY");
    };

    private Query<OrganizationalRole> person_OrganizationalRoleListQuery;

    public OrganizationalRoleDao(DaoConfig config) {
        super(config);
    }
    
    public OrganizationalRoleDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String sql = "CREATE TABLE " + (ifNotExists? "IF NOT EXISTS ": "") + "'ORGANIZATIONAL_ROLE' (" + //
                "'_ID' INTEGER PRIMARY KEY ," + // 0: _id
                "'PERSON_ID' INTEGER," + // 1: person_id
                "'ORG_ID' INTEGER," + // 2: org_id
                "'ROLE' TEXT," + // 3: role
                "'NAME' TEXT," + // 4: name
                "'PRIMARY' INTEGER);"; // 5: primary
        db.execSQL(sql);
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ORGANIZATIONAL_ROLE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, OrganizationalRole entity) {
        stmt.clearBindings();
 
        Integer _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        Integer person_id = entity.getPerson_id();
        if (person_id != null) {
            stmt.bindLong(2, person_id);
        }
 
        Integer org_id = entity.getOrg_id();
        if (org_id != null) {
            stmt.bindLong(3, org_id);
        }
 
        String role = entity.getRole();
        if (role != null) {
            stmt.bindString(4, role);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(5, name);
        }
 
        Boolean primary = entity.getPrimary();
        if (primary != null) {
            stmt.bindLong(6, primary ? 1l: 0l);
        }
    }

    /** @inheritdoc */
    @Override
    public Integer readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public OrganizationalRole readEntity(Cursor cursor, int offset) {
        OrganizationalRole entity = new OrganizationalRole( //
            cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0), // _id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // person_id
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // org_id
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // role
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // name
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0 // primary
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, OrganizationalRole entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0));
        entity.setPerson_id(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setOrg_id(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setRole(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPrimary(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
     }
    
    @Override
    protected Integer updateKeyAfterInsert(OrganizationalRole entity, long rowId) {
        // TODO XXX Only Long PKs are supported currently
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Integer getKey(OrganizationalRole entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "organizationalRoleList" to-many relationship of Person. */
    public synchronized List<OrganizationalRole> _queryPerson_OrganizationalRoleList(Integer person_id) {
        if (person_OrganizationalRoleListQuery == null) {
            QueryBuilder<OrganizationalRole> queryBuilder = queryBuilder();
            queryBuilder.where(Properties.Person_id.eq(person_id));
            person_OrganizationalRoleListQuery = queryBuilder.build();
        } else {
            person_OrganizationalRoleListQuery.setParameter(0, person_id);
        }
        return person_OrganizationalRoleListQuery.list();
    }

}
