package com.missionhub.api.model.sql;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table REJOICABLE.
 */
public class Rejoicable {

    private Long id;
    private Long comment_id;
    private String what;

    public Rejoicable() {
    }

    public Rejoicable(Long id) {
        this.id = id;
    }

    public Rejoicable(Long id, Long comment_id, String what) {
        this.id = id;
        this.comment_id = comment_id;
        this.what = what;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getComment_id() {
        return comment_id;
    }

    public void setComment_id(Long comment_id) {
        this.comment_id = comment_id;
    }

    public String getWhat() {
        return what;
    }

    public void setWhat(String what) {
        this.what = what;
    }

}
