package com.missionhub.api.model.sql;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table REJOICABLE (schema version 1).
 */
public class Rejoicable {

    private Integer _id;
    private Integer comment_id;
    private String what;

    public Rejoicable() {
    }

    public Rejoicable(Integer _id) {
        this._id = _id;
    }

    public Rejoicable(Integer _id, Integer comment_id, String what) {
        this._id = _id;
        this.comment_id = comment_id;
        this.what = what;
    }

    public Integer get_id() {
        return _id;
    }

    public void set_id(Integer _id) {
        this._id = _id;
    }

    public Integer getComment_id() {
        return comment_id;
    }

    public void setComment_id(Integer comment_id) {
        this.comment_id = comment_id;
    }

    public String getWhat() {
        return what;
    }

    public void setWhat(String what) {
        this.what = what;
    }

}
