package com.missionhub.model.sql;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table QUESTION_CHOICE (schema version 1).
 */
public class QuestionChoice {

    private Integer _id;
    private Integer question_id;
    private String choice;

    public QuestionChoice() {
    }

    public QuestionChoice(Integer _id) {
        this._id = _id;
    }

    public QuestionChoice(Integer _id, Integer question_id, String choice) {
        this._id = _id;
        this.question_id = question_id;
        this.choice = choice;
    }

    public Integer get_id() {
        return _id;
    }

    public void set_id(Integer _id) {
        this._id = _id;
    }

    public Integer getQuestion_id() {
        return question_id;
    }

    public void setQuestion_id(Integer question_id) {
        this.question_id = question_id;
    }

    public String getChoice() {
        return choice;
    }

    public void setChoice(String choice) {
        this.choice = choice;
    }

}
