package com.missionhub.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table ASSIGNMENT.
 */
public class Assignment {

    private Long id;
    private Long assigned_to_id;
    private Long person_id;
    private Long organization_id;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Assignment() {
    }

    public Assignment(Long id) {
        this.id = id;
    }

    public Assignment(Long id, Long assigned_to_id, Long person_id, Long organization_id) {
        this.id = id;
        this.assigned_to_id = assigned_to_id;
        this.person_id = person_id;
        this.organization_id = organization_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAssigned_to_id() {
        return assigned_to_id;
    }

    public void setAssigned_to_id(Long assigned_to_id) {
        this.assigned_to_id = assigned_to_id;
    }

    public Long getPerson_id() {
        return person_id;
    }

    public void setPerson_id(Long person_id) {
        this.person_id = person_id;
    }

    public Long getOrganization_id() {
        return organization_id;
    }

    public void setOrganization_id(Long organization_id) {
        this.organization_id = organization_id;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
