package com.missionhub.model;

import java.util.ArrayList;
import java.util.List;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.Query;
import de.greenrobot.dao.QueryBuilder;
import de.greenrobot.dao.SqlUtils;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * DAO for table GROUP_LABELS.
 */
public class GroupLabelsDao extends AbstractDao<GroupLabels, Long> {

	public static final String TABLENAME = "GROUP_LABELS";

	/**
	 * Properties of entity GroupLabels.<br/>
	 * Can be used for QueryBuilder and for referencing column names.
	 */
	public static class Properties {
		public final static Property Id = new Property(0, Long.class, "id", true, "_id");
		public final static Property Group_id = new Property(1, Long.class, "group_id", false, "GROUP_ID");
		public final static Property Label_id = new Property(2, Long.class, "label_id", false, "LABEL_ID");
	};

	private DaoSession daoSession;

	private Query<GroupLabels> groupLabels_GroupLabelsQuery;
	private Query<GroupLabels> groupLabel_GroupLabelsQuery;

	public GroupLabelsDao(final DaoConfig config) {
		super(config);
	}

	public GroupLabelsDao(final DaoConfig config, final DaoSession daoSession) {
		super(config, daoSession);
		this.daoSession = daoSession;
	}

	/** Creates the underlying database table. */
	public static void createTable(final SQLiteDatabase db, final boolean ifNotExists) {
		final String constraint = ifNotExists ? "IF NOT EXISTS " : "";
		db.execSQL("CREATE TABLE " + constraint + "'GROUP_LABELS' (" + //
				"'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
				"'GROUP_ID' INTEGER," + // 1: group_id
				"'LABEL_ID' INTEGER);"); // 2: label_id
	}

	/** Drops the underlying database table. */
	public static void dropTable(final SQLiteDatabase db, final boolean ifExists) {
		final String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'GROUP_LABELS'";
		db.execSQL(sql);
	}

	/** @inheritdoc */
	@Override
	protected void bindValues(final SQLiteStatement stmt, final GroupLabels entity) {
		stmt.clearBindings();

		final Long id = entity.getId();
		if (id != null) {
			stmt.bindLong(1, id);
		}

		final Long group_id = entity.getGroup_id();
		if (group_id != null) {
			stmt.bindLong(2, group_id);
		}

		final Long label_id = entity.getLabel_id();
		if (label_id != null) {
			stmt.bindLong(3, label_id);
		}
	}

	@Override
	protected void attachEntity(final GroupLabels entity) {
		super.attachEntity(entity);
		entity.__setDaoSession(daoSession);
	}

	/** @inheritdoc */
	@Override
	public Long readKey(final Cursor cursor, final int offset) {
		return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
	}

	/** @inheritdoc */
	@Override
	public GroupLabels readEntity(final Cursor cursor, final int offset) {
		final GroupLabels entity = new GroupLabels( //
				cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
				cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // group_id
				cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // label_id
		);
		return entity;
	}

	/** @inheritdoc */
	@Override
	public void readEntity(final Cursor cursor, final GroupLabels entity, final int offset) {
		entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
		entity.setGroup_id(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
		entity.setLabel_id(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
	}

	/** @inheritdoc */
	@Override
	protected Long updateKeyAfterInsert(final GroupLabels entity, final long rowId) {
		entity.setId(rowId);
		return rowId;
	}

	/** @inheritdoc */
	@Override
	public Long getKey(final GroupLabels entity) {
		if (entity != null) {
			return entity.getId();
		} else {
			return null;
		}
	}

	/** @inheritdoc */
	@Override
	protected boolean isEntityUpdateable() {
		return true;
	}

	/** Internal query to resolve the "GroupLabels" to-many relationship of GroupLabels. */
	public synchronized List<GroupLabels> _queryGroupLabels_GroupLabels(final Long group_id) {
		if (groupLabels_GroupLabelsQuery == null) {
			final QueryBuilder<GroupLabels> queryBuilder = queryBuilder();
			queryBuilder.where(Properties.Group_id.eq(group_id));
			groupLabels_GroupLabelsQuery = queryBuilder.build();
		} else {
			groupLabels_GroupLabelsQuery.setParameter(0, group_id);
		}
		return groupLabels_GroupLabelsQuery.list();
	}

	/** Internal query to resolve the "GroupLabels" to-many relationship of GroupLabel. */
	public synchronized List<GroupLabels> _queryGroupLabel_GroupLabels(final Long label_id) {
		if (groupLabel_GroupLabelsQuery == null) {
			final QueryBuilder<GroupLabels> queryBuilder = queryBuilder();
			queryBuilder.where(Properties.Label_id.eq(label_id));
			groupLabel_GroupLabelsQuery = queryBuilder.build();
		} else {
			groupLabel_GroupLabelsQuery.setParameter(0, label_id);
		}
		return groupLabel_GroupLabelsQuery.list();
	}

	private String selectDeep;

	protected String getSelectDeep() {
		if (selectDeep == null) {
			final StringBuilder builder = new StringBuilder("SELECT ");
			SqlUtils.appendColumns(builder, "T", getAllColumns());
			builder.append(',');
			SqlUtils.appendColumns(builder, "T0", daoSession.getGroupDao().getAllColumns());
			builder.append(',');
			SqlUtils.appendColumns(builder, "T1", daoSession.getGroupLabelDao().getAllColumns());
			builder.append(" FROM GROUP_LABELS T");
			builder.append(" LEFT JOIN GROUPS T0 ON T.'GROUP_ID'=T0.'_id'");
			builder.append(" LEFT JOIN GROUP_LABEL T1 ON T.'LABEL_ID'=T1.'_id'");
			builder.append(' ');
			selectDeep = builder.toString();
		}
		return selectDeep;
	}

	protected GroupLabels loadCurrentDeep(final Cursor cursor, final boolean lock) {
		final GroupLabels entity = loadCurrent(cursor, 0, lock);
		int offset = getAllColumns().length;

		final Group group = loadCurrentOther(daoSession.getGroupDao(), cursor, offset);
		entity.setGroup(group);
		offset += daoSession.getGroupDao().getAllColumns().length;

		final GroupLabel groupLabel = loadCurrentOther(daoSession.getGroupLabelDao(), cursor, offset);
		entity.setGroupLabel(groupLabel);

		return entity;
	}

	public GroupLabels loadDeep(final Long key) {
		assertSinglePk();
		if (key == null) {
			return null;
		}

		final StringBuilder builder = new StringBuilder(getSelectDeep());
		builder.append("WHERE ");
		SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
		final String sql = builder.toString();

		final String[] keyArray = new String[] { key.toString() };
		final Cursor cursor = db.rawQuery(sql, keyArray);

		try {
			final boolean available = cursor.moveToFirst();
			if (!available) {
				return null;
			} else if (!cursor.isLast()) {
				throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
			}
			return loadCurrentDeep(cursor, true);
		} finally {
			cursor.close();
		}
	}

	/** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
	public List<GroupLabels> loadAllDeepFromCursor(final Cursor cursor) {
		final int count = cursor.getCount();
		final List<GroupLabels> list = new ArrayList<GroupLabels>(count);

		if (cursor.moveToFirst()) {
			if (identityScope != null) {
				identityScope.lock();
				identityScope.reserveRoom(count);
			}
			try {
				do {
					list.add(loadCurrentDeep(cursor, false));
				} while (cursor.moveToNext());
			} finally {
				if (identityScope != null) {
					identityScope.unlock();
				}
			}
		}
		return list;
	}

	protected List<GroupLabels> loadDeepAllAndCloseCursor(final Cursor cursor) {
		try {
			return loadAllDeepFromCursor(cursor);
		} finally {
			cursor.close();
		}
	}

	/** A raw-style query where you can pass any WHERE clause and arguments. */
	public List<GroupLabels> queryDeep(final String where, final String... selectionArg) {
		final Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
		return loadDeepAllAndCloseCursor(cursor);
	}

}
