package com.missionhub.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LOCATION.
 */
public class Location {

	private Long id;
	private Long person_id;
	private String name;
	private String location_id;
	private String provider;

	public Location() {}

	public Location(final Long id) {
		this.id = id;
	}

	public Location(final Long id, final Long person_id, final String name, final String location_id, final String provider) {
		this.id = id;
		this.person_id = person_id;
		this.name = name;
		this.location_id = location_id;
		this.provider = provider;
	}

	public Long getId() {
		return id;
	}

	public void setId(final Long id) {
		this.id = id;
	}

	public Long getPerson_id() {
		return person_id;
	}

	public void setPerson_id(final Long person_id) {
		this.person_id = person_id;
	}

	public String getName() {
		return name;
	}

	public void setName(final String name) {
		this.name = name;
	}

	public String getLocation_id() {
		return location_id;
	}

	public void setLocation_id(final String location_id) {
		this.location_id = location_id;
	}

	public String getProvider() {
		return provider;
	}

	public void setProvider(final String provider) {
		this.provider = provider;
	}

}
