package com.missionhub.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table QUESTION_CHOICE.
 */
public class QuestionChoice {

	private Long id;
	private Long question_id;
	private String choice;

	public QuestionChoice() {}

	public QuestionChoice(final Long id) {
		this.id = id;
	}

	public QuestionChoice(final Long id, final Long question_id, final String choice) {
		this.id = id;
		this.question_id = question_id;
		this.choice = choice;
	}

	public Long getId() {
		return id;
	}

	public void setId(final Long id) {
		this.id = id;
	}

	public Long getQuestion_id() {
		return question_id;
	}

	public void setQuestion_id(final Long question_id) {
		this.question_id = question_id;
	}

	public String getChoice() {
		return choice;
	}

	public void setChoice(final String choice) {
		this.choice = choice;
	}

}
