package com.missionhub.model;

import java.util.ArrayList;
import java.util.List;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.SqlUtils;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * DAO for table USER_SETTING.
 */
public class UserSettingDao extends AbstractDao<UserSetting, Long> {

	public static final String TABLENAME = "USER_SETTING";

	/**
	 * Properties of entity UserSetting.<br/>
	 * Can be used for QueryBuilder and for referencing column names.
	 */
	public static class Properties {
		public final static Property Id = new Property(0, Long.class, "id", true, "_id");
		public final static Property Person_id = new Property(1, Long.class, "person_id", false, "PERSON_ID");
		public final static Property Key = new Property(2, String.class, "key", false, "KEY");
		public final static Property Value = new Property(3, String.class, "value", false, "VALUE");
	};

	private DaoSession daoSession;

	public UserSettingDao(final DaoConfig config) {
		super(config);
	}

	public UserSettingDao(final DaoConfig config, final DaoSession daoSession) {
		super(config, daoSession);
		this.daoSession = daoSession;
	}

	/** Creates the underlying database table. */
	public static void createTable(final SQLiteDatabase db, final boolean ifNotExists) {
		final String constraint = ifNotExists ? "IF NOT EXISTS " : "";
		db.execSQL("CREATE TABLE " + constraint + "'USER_SETTING' (" + //
				"'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
				"'PERSON_ID' INTEGER," + // 1: person_id
				"'KEY' TEXT," + // 2: key
				"'VALUE' TEXT);"); // 3: value
	}

	/** Drops the underlying database table. */
	public static void dropTable(final SQLiteDatabase db, final boolean ifExists) {
		final String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'USER_SETTING'";
		db.execSQL(sql);
	}

	/** @inheritdoc */
	@Override
	protected void bindValues(final SQLiteStatement stmt, final UserSetting entity) {
		stmt.clearBindings();

		final Long id = entity.getId();
		if (id != null) {
			stmt.bindLong(1, id);
		}

		final Long person_id = entity.getPerson_id();
		if (person_id != null) {
			stmt.bindLong(2, person_id);
		}

		final String key = entity.getKey();
		if (key != null) {
			stmt.bindString(3, key);
		}

		final String value = entity.getValue();
		if (value != null) {
			stmt.bindString(4, value);
		}
	}

	@Override
	protected void attachEntity(final UserSetting entity) {
		super.attachEntity(entity);
		entity.__setDaoSession(daoSession);
	}

	/** @inheritdoc */
	@Override
	public Long readKey(final Cursor cursor, final int offset) {
		return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
	}

	/** @inheritdoc */
	@Override
	public UserSetting readEntity(final Cursor cursor, final int offset) {
		final UserSetting entity = new UserSetting( //
				cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
				cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // person_id
				cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // key
				cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // value
		);
		return entity;
	}

	/** @inheritdoc */
	@Override
	public void readEntity(final Cursor cursor, final UserSetting entity, final int offset) {
		entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
		entity.setPerson_id(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
		entity.setKey(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
		entity.setValue(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
	}

	/** @inheritdoc */
	@Override
	protected Long updateKeyAfterInsert(final UserSetting entity, final long rowId) {
		entity.setId(rowId);
		return rowId;
	}

	/** @inheritdoc */
	@Override
	public Long getKey(final UserSetting entity) {
		if (entity != null) {
			return entity.getId();
		} else {
			return null;
		}
	}

	/** @inheritdoc */
	@Override
	protected boolean isEntityUpdateable() {
		return true;
	}

	private String selectDeep;

	protected String getSelectDeep() {
		if (selectDeep == null) {
			final StringBuilder builder = new StringBuilder("SELECT ");
			SqlUtils.appendColumns(builder, "T", getAllColumns());
			builder.append(',');
			SqlUtils.appendColumns(builder, "T0", daoSession.getPersonDao().getAllColumns());
			builder.append(" FROM USER_SETTING T");
			builder.append(" LEFT JOIN PERSON T0 ON T.'PERSON_ID'=T0.'_id'");
			builder.append(' ');
			selectDeep = builder.toString();
		}
		return selectDeep;
	}

	protected UserSetting loadCurrentDeep(final Cursor cursor, final boolean lock) {
		final UserSetting entity = loadCurrent(cursor, 0, lock);
		final int offset = getAllColumns().length;

		final Person person = loadCurrentOther(daoSession.getPersonDao(), cursor, offset);
		entity.setPerson(person);

		return entity;
	}

	public UserSetting loadDeep(final Long key) {
		assertSinglePk();
		if (key == null) {
			return null;
		}

		final StringBuilder builder = new StringBuilder(getSelectDeep());
		builder.append("WHERE ");
		SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
		final String sql = builder.toString();

		final String[] keyArray = new String[] { key.toString() };
		final Cursor cursor = db.rawQuery(sql, keyArray);

		try {
			final boolean available = cursor.moveToFirst();
			if (!available) {
				return null;
			} else if (!cursor.isLast()) {
				throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
			}
			return loadCurrentDeep(cursor, true);
		} finally {
			cursor.close();
		}
	}

	/** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
	public List<UserSetting> loadAllDeepFromCursor(final Cursor cursor) {
		final int count = cursor.getCount();
		final List<UserSetting> list = new ArrayList<UserSetting>(count);

		if (cursor.moveToFirst()) {
			if (identityScope != null) {
				identityScope.lock();
				identityScope.reserveRoom(count);
			}
			try {
				do {
					list.add(loadCurrentDeep(cursor, false));
				} while (cursor.moveToNext());
			} finally {
				if (identityScope != null) {
					identityScope.unlock();
				}
			}
		}
		return list;
	}

	protected List<UserSetting> loadDeepAllAndCloseCursor(final Cursor cursor) {
		try {
			return loadAllDeepFromCursor(cursor);
		} finally {
			cursor.close();
		}
	}

	/** A raw-style query where you can pass any WHERE clause and arguments. */
	public List<UserSetting> queryDeep(final String where, final String... selectionArg) {
		final Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
		return loadDeepAllAndCloseCursor(cursor);
	}

}
