package com.missionhub.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.missionhub.model.User;
import com.missionhub.model.Person;
import com.missionhub.model.Address;
import com.missionhub.model.EmailAddress;
import com.missionhub.model.PhoneNumber;
import com.missionhub.model.Organization;
import com.missionhub.model.Label;
import com.missionhub.model.Permission;
import com.missionhub.model.OrganizationalLabel;
import com.missionhub.model.OrganizationalPermission;
import com.missionhub.model.ContactAssignment;
import com.missionhub.model.Interaction;
import com.missionhub.model.InteractionInitiator;
import com.missionhub.model.InteractionType;
import com.missionhub.model.Question;
import com.missionhub.model.Survey;
import com.missionhub.model.SmsKeyword;
import com.missionhub.model.AnswerSheet;
import com.missionhub.model.Answer;
import com.missionhub.model.Setting;
import com.missionhub.model.UserSetting;

import com.missionhub.model.UserDao;
import com.missionhub.model.PersonDao;
import com.missionhub.model.AddressDao;
import com.missionhub.model.EmailAddressDao;
import com.missionhub.model.PhoneNumberDao;
import com.missionhub.model.OrganizationDao;
import com.missionhub.model.LabelDao;
import com.missionhub.model.PermissionDao;
import com.missionhub.model.OrganizationalLabelDao;
import com.missionhub.model.OrganizationalPermissionDao;
import com.missionhub.model.ContactAssignmentDao;
import com.missionhub.model.InteractionDao;
import com.missionhub.model.InteractionInitiatorDao;
import com.missionhub.model.InteractionTypeDao;
import com.missionhub.model.QuestionDao;
import com.missionhub.model.SurveyDao;
import com.missionhub.model.SmsKeywordDao;
import com.missionhub.model.AnswerSheetDao;
import com.missionhub.model.AnswerDao;
import com.missionhub.model.SettingDao;
import com.missionhub.model.UserSettingDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig personDaoConfig;
    private final DaoConfig addressDaoConfig;
    private final DaoConfig emailAddressDaoConfig;
    private final DaoConfig phoneNumberDaoConfig;
    private final DaoConfig organizationDaoConfig;
    private final DaoConfig labelDaoConfig;
    private final DaoConfig permissionDaoConfig;
    private final DaoConfig organizationalLabelDaoConfig;
    private final DaoConfig organizationalPermissionDaoConfig;
    private final DaoConfig contactAssignmentDaoConfig;
    private final DaoConfig interactionDaoConfig;
    private final DaoConfig interactionInitiatorDaoConfig;
    private final DaoConfig interactionTypeDaoConfig;
    private final DaoConfig questionDaoConfig;
    private final DaoConfig surveyDaoConfig;
    private final DaoConfig smsKeywordDaoConfig;
    private final DaoConfig answerSheetDaoConfig;
    private final DaoConfig answerDaoConfig;
    private final DaoConfig settingDaoConfig;
    private final DaoConfig userSettingDaoConfig;

    private final UserDao userDao;
    private final PersonDao personDao;
    private final AddressDao addressDao;
    private final EmailAddressDao emailAddressDao;
    private final PhoneNumberDao phoneNumberDao;
    private final OrganizationDao organizationDao;
    private final LabelDao labelDao;
    private final PermissionDao permissionDao;
    private final OrganizationalLabelDao organizationalLabelDao;
    private final OrganizationalPermissionDao organizationalPermissionDao;
    private final ContactAssignmentDao contactAssignmentDao;
    private final InteractionDao interactionDao;
    private final InteractionInitiatorDao interactionInitiatorDao;
    private final InteractionTypeDao interactionTypeDao;
    private final QuestionDao questionDao;
    private final SurveyDao surveyDao;
    private final SmsKeywordDao smsKeywordDao;
    private final AnswerSheetDao answerSheetDao;
    private final AnswerDao answerDao;
    private final SettingDao settingDao;
    private final UserSettingDao userSettingDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        addressDaoConfig = daoConfigMap.get(AddressDao.class).clone();
        addressDaoConfig.initIdentityScope(type);

        emailAddressDaoConfig = daoConfigMap.get(EmailAddressDao.class).clone();
        emailAddressDaoConfig.initIdentityScope(type);

        phoneNumberDaoConfig = daoConfigMap.get(PhoneNumberDao.class).clone();
        phoneNumberDaoConfig.initIdentityScope(type);

        organizationDaoConfig = daoConfigMap.get(OrganizationDao.class).clone();
        organizationDaoConfig.initIdentityScope(type);

        labelDaoConfig = daoConfigMap.get(LabelDao.class).clone();
        labelDaoConfig.initIdentityScope(type);

        permissionDaoConfig = daoConfigMap.get(PermissionDao.class).clone();
        permissionDaoConfig.initIdentityScope(type);

        organizationalLabelDaoConfig = daoConfigMap.get(OrganizationalLabelDao.class).clone();
        organizationalLabelDaoConfig.initIdentityScope(type);

        organizationalPermissionDaoConfig = daoConfigMap.get(OrganizationalPermissionDao.class).clone();
        organizationalPermissionDaoConfig.initIdentityScope(type);

        contactAssignmentDaoConfig = daoConfigMap.get(ContactAssignmentDao.class).clone();
        contactAssignmentDaoConfig.initIdentityScope(type);

        interactionDaoConfig = daoConfigMap.get(InteractionDao.class).clone();
        interactionDaoConfig.initIdentityScope(type);

        interactionInitiatorDaoConfig = daoConfigMap.get(InteractionInitiatorDao.class).clone();
        interactionInitiatorDaoConfig.initIdentityScope(type);

        interactionTypeDaoConfig = daoConfigMap.get(InteractionTypeDao.class).clone();
        interactionTypeDaoConfig.initIdentityScope(type);

        questionDaoConfig = daoConfigMap.get(QuestionDao.class).clone();
        questionDaoConfig.initIdentityScope(type);

        surveyDaoConfig = daoConfigMap.get(SurveyDao.class).clone();
        surveyDaoConfig.initIdentityScope(type);

        smsKeywordDaoConfig = daoConfigMap.get(SmsKeywordDao.class).clone();
        smsKeywordDaoConfig.initIdentityScope(type);

        answerSheetDaoConfig = daoConfigMap.get(AnswerSheetDao.class).clone();
        answerSheetDaoConfig.initIdentityScope(type);

        answerDaoConfig = daoConfigMap.get(AnswerDao.class).clone();
        answerDaoConfig.initIdentityScope(type);

        settingDaoConfig = daoConfigMap.get(SettingDao.class).clone();
        settingDaoConfig.initIdentityScope(type);

        userSettingDaoConfig = daoConfigMap.get(UserSettingDao.class).clone();
        userSettingDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        personDao = new PersonDao(personDaoConfig, this);
        addressDao = new AddressDao(addressDaoConfig, this);
        emailAddressDao = new EmailAddressDao(emailAddressDaoConfig, this);
        phoneNumberDao = new PhoneNumberDao(phoneNumberDaoConfig, this);
        organizationDao = new OrganizationDao(organizationDaoConfig, this);
        labelDao = new LabelDao(labelDaoConfig, this);
        permissionDao = new PermissionDao(permissionDaoConfig, this);
        organizationalLabelDao = new OrganizationalLabelDao(organizationalLabelDaoConfig, this);
        organizationalPermissionDao = new OrganizationalPermissionDao(organizationalPermissionDaoConfig, this);
        contactAssignmentDao = new ContactAssignmentDao(contactAssignmentDaoConfig, this);
        interactionDao = new InteractionDao(interactionDaoConfig, this);
        interactionInitiatorDao = new InteractionInitiatorDao(interactionInitiatorDaoConfig, this);
        interactionTypeDao = new InteractionTypeDao(interactionTypeDaoConfig, this);
        questionDao = new QuestionDao(questionDaoConfig, this);
        surveyDao = new SurveyDao(surveyDaoConfig, this);
        smsKeywordDao = new SmsKeywordDao(smsKeywordDaoConfig, this);
        answerSheetDao = new AnswerSheetDao(answerSheetDaoConfig, this);
        answerDao = new AnswerDao(answerDaoConfig, this);
        settingDao = new SettingDao(settingDaoConfig, this);
        userSettingDao = new UserSettingDao(userSettingDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Person.class, personDao);
        registerDao(Address.class, addressDao);
        registerDao(EmailAddress.class, emailAddressDao);
        registerDao(PhoneNumber.class, phoneNumberDao);
        registerDao(Organization.class, organizationDao);
        registerDao(Label.class, labelDao);
        registerDao(Permission.class, permissionDao);
        registerDao(OrganizationalLabel.class, organizationalLabelDao);
        registerDao(OrganizationalPermission.class, organizationalPermissionDao);
        registerDao(ContactAssignment.class, contactAssignmentDao);
        registerDao(Interaction.class, interactionDao);
        registerDao(InteractionInitiator.class, interactionInitiatorDao);
        registerDao(InteractionType.class, interactionTypeDao);
        registerDao(Question.class, questionDao);
        registerDao(Survey.class, surveyDao);
        registerDao(SmsKeyword.class, smsKeywordDao);
        registerDao(AnswerSheet.class, answerSheetDao);
        registerDao(Answer.class, answerDao);
        registerDao(Setting.class, settingDao);
        registerDao(UserSetting.class, userSettingDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        personDaoConfig.getIdentityScope().clear();
        addressDaoConfig.getIdentityScope().clear();
        emailAddressDaoConfig.getIdentityScope().clear();
        phoneNumberDaoConfig.getIdentityScope().clear();
        organizationDaoConfig.getIdentityScope().clear();
        labelDaoConfig.getIdentityScope().clear();
        permissionDaoConfig.getIdentityScope().clear();
        organizationalLabelDaoConfig.getIdentityScope().clear();
        organizationalPermissionDaoConfig.getIdentityScope().clear();
        contactAssignmentDaoConfig.getIdentityScope().clear();
        interactionDaoConfig.getIdentityScope().clear();
        interactionInitiatorDaoConfig.getIdentityScope().clear();
        interactionTypeDaoConfig.getIdentityScope().clear();
        questionDaoConfig.getIdentityScope().clear();
        surveyDaoConfig.getIdentityScope().clear();
        smsKeywordDaoConfig.getIdentityScope().clear();
        answerSheetDaoConfig.getIdentityScope().clear();
        answerDaoConfig.getIdentityScope().clear();
        settingDaoConfig.getIdentityScope().clear();
        userSettingDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

    public AddressDao getAddressDao() {
        return addressDao;
    }

    public EmailAddressDao getEmailAddressDao() {
        return emailAddressDao;
    }

    public PhoneNumberDao getPhoneNumberDao() {
        return phoneNumberDao;
    }

    public OrganizationDao getOrganizationDao() {
        return organizationDao;
    }

    public LabelDao getLabelDao() {
        return labelDao;
    }

    public PermissionDao getPermissionDao() {
        return permissionDao;
    }

    public OrganizationalLabelDao getOrganizationalLabelDao() {
        return organizationalLabelDao;
    }

    public OrganizationalPermissionDao getOrganizationalPermissionDao() {
        return organizationalPermissionDao;
    }

    public ContactAssignmentDao getContactAssignmentDao() {
        return contactAssignmentDao;
    }

    public InteractionDao getInteractionDao() {
        return interactionDao;
    }

    public InteractionInitiatorDao getInteractionInitiatorDao() {
        return interactionInitiatorDao;
    }

    public InteractionTypeDao getInteractionTypeDao() {
        return interactionTypeDao;
    }

    public QuestionDao getQuestionDao() {
        return questionDao;
    }

    public SurveyDao getSurveyDao() {
        return surveyDao;
    }

    public SmsKeywordDao getSmsKeywordDao() {
        return smsKeywordDao;
    }

    public AnswerSheetDao getAnswerSheetDao() {
        return answerSheetDao;
    }

    public AnswerDao getAnswerDao() {
        return answerDao;
    }

    public SettingDao getSettingDao() {
        return settingDao;
    }

    public UserSettingDao getUserSettingDao() {
        return userSettingDao;
    }

}
